on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  legacy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["12.0.2", "19.0.3-legacy", "25.0.2"]
      fail-fast: false
    steps:
      - name: Customized Keycloak Docker setup
        run: |
          docker run --name keycloak_server -d -p 8180:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=password quay.io/keycloak/keycloak:${{ matrix.version }} start-dev
          sleep 120

      - name: Keycloak Admin CLI
        uses: carlosthe19916/keycloak-action@master
        with:
          version: ${{ matrix.version }}
          server: http://keycloak:8080
          username: admin
          password: password
          kcadm: get realms
